"""
Django settings for epivar project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()  # take environment variables

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", default="")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY is not set in the environment variables")

FIELD_ENCRYPTION_KEY = os.environ.get("FIELD_ENCRYPTION_KEY", "")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

if DEBUG:
    ALLOWED_HOSTS = ("localhost", "127.0.0.1")
    CSRF_TRUSTED_ORIGINS = ("http://localhost:8081", "http://127.0.0.1:8081")
else:
    ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "").split(",")
    CSRF_TRUSTED_ORIGINS = os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")


USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = False


# Application definition
INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.admindocs",

    # Installed
    "django_minio_backend.apps.DjangoMinioBackendConfig",
    "encrypted_model_fields",
    "django_celery_results",
    "crispy_bootstrap5",
    "django_addanother",
    "django_select2",
    "crispy_forms",
    "polymorphic",
    "reversion",
    "formtools",
    "tinymce",

    # Internal
    "cms",
    "users",
    "studies",
    "analyses",
    "datasets",
    "ontologies",
    "reference_genomes",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "epivar.urls"
LOGIN_URL = "/user/sign_in/"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "epivar.wsgi.application"

# Logging
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
    },
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": True,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Default
DATABASES = {
    "default": {
        "NAME": os.environ.get("DB_NAME", ""),
        "ENGINE": "django.db.backends.postgresql",
        "USER": os.environ.get("DB_USER", ""),
        "PASSWORD": os.environ.get("DB_PASS", ""),
        "HOST": os.getenv("DB_HOST", default="127.0.0.1"),
        "PORT": os.getenv("DB_PORT", default=5432),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "users.User"
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Warsaw"

USE_I18N = True

USE_TZ = True

# SUPERUSER
DJANGO_SUPERUSER_PASSWORD = os.environ.get("DJANGO_SUPERUSER_PASSWORD")
DJANGO_SUPERUSER_USERNAME = os.environ.get("DJANGO_SUPERUSER_USERNAME")
DJANGO_SUPERUSER_EMAIL = os.environ.get("DJANGO_SUPERUSER_EMAIL")

# Minio
# Storages definition (from django 4.2), for static and media files
# Configured for Minio backend, but also configurable for AWS S3

def strip_scheme(url: str) -> str:
    return url.replace("http://", "").replace("https://", "").rstrip("/")


MINIO_ENDPOINT_URL = os.environ["MINIO_ENDPOINT_URL"]      # internal, e.g. http://minio:9000
MINIO_PUBLIC_URL = os.environ["MINIO_PUBLIC_URL"]          # public, e.g. http://s3.localhost:8081

MINIO_ENDPOINT = strip_scheme(MINIO_ENDPOINT_URL)          # -> minio:9000
MINIO_EXTERNAL_ENDPOINT = strip_scheme(MINIO_PUBLIC_URL)   # -> s3.localhost:8081

MINIO_EXTERNAL_ENDPOINT_USE_HTTPS = MINIO_PUBLIC_URL.startswith("https://")
MINIO_USE_HTTPS = MINIO_ENDPOINT_URL.startswith("https://")

MINIO_ACCESS_KEY = os.environ["MINIO_ROOT_USER"]
MINIO_SECRET_KEY = os.environ["MINIO_ROOT_PASSWORD"]

MINIO_REGION = os.environ["MINIO_REGION"]
MINIO_DEFAULT_BUCKET = os.environ["MINIO_DEFAULT_BUCKET"]
MINIO_STATIC_BUCKET = os.environ["MINIO_STATIC_BUCKET"]


STORAGES = {
    "staticfiles": {
        "BACKEND": "django_minio_backend.models.MinioBackendStatic",
        "OPTIONS": {
            "MINIO_ENDPOINT": MINIO_ENDPOINT,
            "MINIO_EXTERNAL_ENDPOINT": MINIO_EXTERNAL_ENDPOINT,
            "MINIO_EXTERNAL_ENDPOINT_USE_HTTPS": MINIO_EXTERNAL_ENDPOINT_USE_HTTPS,
            "MINIO_ACCESS_KEY": MINIO_ACCESS_KEY,
            "MINIO_SECRET_KEY": MINIO_SECRET_KEY,
            "MINIO_USE_HTTPS": MINIO_USE_HTTPS,
            "MINIO_REGION": MINIO_REGION,
            "MINIO_URL_EXPIRY_HOURS": timedelta(days=1),
            "MINIO_CONSISTENCY_CHECK_ON_START": True,
            "MINIO_STATIC_FILES_BUCKET": MINIO_STATIC_BUCKET,
        },
    },
    "default": {
        "BACKEND": "django_minio_backend.models.MinioBackend",
        "OPTIONS": {
            "MINIO_ENDPOINT": MINIO_ENDPOINT,
            "MINIO_EXTERNAL_ENDPOINT": MINIO_EXTERNAL_ENDPOINT,
            "MINIO_EXTERNAL_ENDPOINT_USE_HTTPS": MINIO_EXTERNAL_ENDPOINT_USE_HTTPS,
            "MINIO_ACCESS_KEY": MINIO_ACCESS_KEY,
            "MINIO_SECRET_KEY": MINIO_SECRET_KEY,
            "MINIO_USE_HTTPS": MINIO_USE_HTTPS,
            "MINIO_REGION": MINIO_REGION,
            "MINIO_PRIVATE_BUCKETS": [MINIO_DEFAULT_BUCKET],
            "MINIO_PUBLIC_BUCKETS": [MINIO_STATIC_BUCKET],
            "MINIO_URL_EXPIRY_HOURS": timedelta(days=1),
            "MINIO_CONSISTENCY_CHECK_ON_START": False,
            "MINIO_DEFAULT_BUCKET": MINIO_DEFAULT_BUCKET,
            "MINIO_STATIC_FILES_BUCKET": MINIO_STATIC_BUCKET,
            "MINIO_BUCKET_CHECK_ON_SAVE": False,
        },
    },
}
print(STORAGES)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATICFILES_DIRS = [
    ("logos", os.path.join(BASE_DIR, "assets", "logos")),
    ("images", os.path.join(BASE_DIR, "assets", "images")),
]

# Media files
# https://docs.djangoproject.com/en/5.2/topics/files/
STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Celery
CELERY_RESULT_BACKEND = "django-db"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE")

CELERY_RESULT_EXTENDED = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": 3600,
    "retry_policy": {"interval_start": 0, "interval_step": 1, "interval_max": 3},
}

# Broker config
host = os.getenv("REDIS_HOST", default="127.0.0.1")
passwd = os.getenv("REDIS_PASS", default="pass")
port = os.getenv("REDIS_PORT", default=6379)

# BROKER URL
CELERY_BROKER_URL = f"redis://:{passwd}@{host}:{port}/0"
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# CACHE
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://:{passwd}@{host}:{port}/0",
    }
}

SELECT2_CACHE_BACKEND = "default"

# SMTP
# DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "webmaster@example.com")
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_HOST_USER = os.getenv("EMAIL", default="user")
# EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASS", default="pass")
# EMAIL_USE_TLS = True

# Crispy
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"
