# Generated by Django 5.2.4 on 2025-10-14 11:47

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("name", models.SlugField(primary_key=True, serialize=False)),
                (
                    "creation_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("content", tinymce.models.HTMLField(blank=True, null=True)),
            ],
        ),
    ]
