# Generated by Django 5.2.4 on 2025-10-14 12:01

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsortiumMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("institution", models.CharField(max_length=255)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Upload institution logo (PNG/JPG/SVG).",
                        null=True,
                        upload_to=cms.models.logo_upload_path,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
    ]
