# Generated by Django 5.2.4 on 2025-09-10 13:13

import analyses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("datasets", "0002_initial"),
        ("django_celery_results", "0014_alter_taskresult_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gsea", "GSEA"),
                            ("stats", "Genomic statistics"),
                            ("volcano_plot", "Volcano plot"),
                            ("meta_analysis", "Meta analysis"),
                            ("manhattan_plot", "Manhattan plot"),
                            ("intersection_report", "Intersection report"),
                            ("reference_epigenome", "Reference epigenome"),
                        ]
                    ),
                ),
                ("parameters", models.JSONField(blank=True, null=True)),
                ("results", models.JSONField(blank=True, null=True)),
                (
                    "result_file",
                    models.FileField(
                        blank=True, null=True, upload_to=analyses.models.data_path
                    ),
                ),
                (
                    "result_file_checksum",
                    models.CharField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_task",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_results.taskresult",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="datasets.basedata",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Analyses",
            },
        ),
    ]
