# Generated by Django 5.2.4 on 2025-09-15 07:30

import analyses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="category",
            field=models.CharField(
                choices=[
                    ("gsea", "GSEA"),
                    ("stats", "Genomic statistics"),
                    ("volcano_plot", "Volcano plot"),
                    ("meta_analysis", "Meta analysis"),
                    ("manhattan_plot", "Manhattan plot"),
                    ("intersection_report", "Intersection report"),
                    ("reference_epigenome", "Reference epigenome"),
                ],
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="parameters",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="result_file",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to=analyses.models.data_path,
            ),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="results",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
