# Generated by Django 5.2.4 on 2025-09-15 08:07

import analyses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0002_alter_analysis_category_alter_analysis_parameters_and_more"),
        ("datasets", "0003_dataset"),
        ("django_celery_results", "0014_alter_taskresult_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="GSEAAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("require_same_strandedness", models.BooleanField(default=False)),
                ("minimum_overlap_required", models.FloatField(default=1e-09)),
                (
                    "correction_method",
                    models.CharField(
                        choices=[
                            ("bonferroni", "Bonferroni"),
                            ("sidak", "Šidák"),
                            ("holm", "Holm"),
                            ("holm-sidak", "Holm-Šidák"),
                            ("smm", "Simes-Hochberg"),
                            ("hommel", "Hommel"),
                            ("fdr_bh", "Benjamini/Hochberg (FDR)"),
                            ("fdr_by", "Benjamini/Yekutieli (FDR)"),
                            ("fdr_tsbh", "Two-stage Benjamini/Hochberg (FDR)"),
                            (
                                "fdr_tsbky",
                                "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                            ),
                        ],
                        default="fdr_by",
                    ),
                ),
                ("results", models.JSONField(blank=True, editable=False, null=True)),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to=analyses.models.data_path,
                    ),
                ),
                (
                    "result_file_checksum",
                    models.CharField(blank=True, editable=False, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_task",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_results.taskresult",
                    ),
                ),
                (
                    "background",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsea_background",
                        to="datasets.dataset",
                    ),
                ),
                (
                    "foreground",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gsea_foreground",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Analyses",
            },
        ),
        migrations.DeleteModel(
            name="Analysis",
        ),
    ]
