# Generated by Django 5.2.4 on 2025-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0003_gseaanalysis_delete_analysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="gseaanalysis",
            name="adjust_for_background",
            field=models.BooleanField(default=False),
        ),
    ]
