# Generated by Django 5.2.4 on 2025-09-15 10:14

import analyses.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0004_gseaanalysis_adjust_for_background"),
        ("reference_genomes", "0002_alter_geneset_collection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gseaanalysis",
            options={"verbose_name_plural": "GSEA"},
        ),
        migrations.RemoveField(
            model_name="gseaanalysis",
            name="adjust_for_background",
        ),
        migrations.AddField(
            model_name="gseaanalysis",
            name="reference_genome",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="reference_genomes.referencegenome",
            ),
        ),
        migrations.AddField(
            model_name="gseaanalysis",
            name="significance_level",
            field=models.FloatField(
                default=0.05,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="gseaanalysis",
            name="submitter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gseaanalysis",
            name="universe",
            field=models.CharField(
                choices=[
                    ("H", "Hallmark"),
                    ("C1", "Positional gene sets"),
                    ("C2", "Curated gene sets"),
                    ("C3", "Regulatory target gene sets"),
                    ("C4", "Computational gene sets"),
                    ("C5", "Ontology gene sets"),
                    ("C6", "Oncogenic signature gene sets"),
                    ("C7", "Immunologic signature gene sets"),
                    ("C8", "Cell type signature gene sets"),
                    ("all", "ALL"),
                ],
                default="all",
            ),
        ),
        migrations.AlterField(
            model_name="gseaanalysis",
            name="background",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=analyses.models.data_path,
                validators=[analyses.models.validate_file],
            ),
        ),
        migrations.AlterField(
            model_name="gseaanalysis",
            name="foreground",
            field=models.FileField(
                upload_to=analyses.models.data_path,
                validators=[analyses.models.validate_file],
            ),
        ),
        migrations.AlterField(
            model_name="gseaanalysis",
            name="minimum_overlap_required",
            field=models.FloatField(
                default=1e-09,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
