# Generated by Django 5.2.4 on 2025-09-15 10:30

import analyses.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0005_alter_gseaanalysis_options_and_more"),
        ("django_celery_results", "0014_alter_taskresult_status"),
        ("reference_genomes", "0002_alter_geneset_collection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GSEA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foreground",
                    models.FileField(
                        upload_to=analyses.models.data_path,
                        validators=[analyses.models.validate_file],
                    ),
                ),
                (
                    "background",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analyses.models.data_path,
                        validators=[analyses.models.validate_file],
                    ),
                ),
                ("require_same_strandedness", models.BooleanField(default=False)),
                (
                    "minimum_overlap_required",
                    models.FloatField(
                        default=1e-09,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "significance_level",
                    models.FloatField(
                        default=0.05,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "correction_method",
                    models.CharField(
                        choices=[
                            ("bonferroni", "Bonferroni"),
                            ("sidak", "Šidák"),
                            ("holm", "Holm"),
                            ("holm-sidak", "Holm-Šidák"),
                            ("smm", "Simes-Hochberg"),
                            ("hommel", "Hommel"),
                            ("fdr_bh", "Benjamini/Hochberg (FDR)"),
                            ("fdr_by", "Benjamini/Yekutieli (FDR)"),
                            ("fdr_tsbh", "Two-stage Benjamini/Hochberg (FDR)"),
                            (
                                "fdr_tsbky",
                                "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                            ),
                        ],
                        default="fdr_by",
                    ),
                ),
                ("results", models.JSONField(blank=True, editable=False, null=True)),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to=analyses.models.data_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "universe",
                    models.CharField(
                        choices=[
                            ("H", "Hallmark"),
                            ("C1", "Positional gene sets"),
                            ("C2", "Curated gene sets"),
                            ("C3", "Regulatory target gene sets"),
                            ("C4", "Computational gene sets"),
                            ("C5", "Ontology gene sets"),
                            ("C6", "Oncogenic signature gene sets"),
                            ("C7", "Immunologic signature gene sets"),
                            ("C8", "Cell type signature gene sets"),
                            ("all", "ALL"),
                        ],
                        default="all",
                    ),
                ),
                (
                    "analysis_task",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_results.taskresult",
                    ),
                ),
                (
                    "reference_genome",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference_genomes.referencegenome",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GSEA",
            },
        ),
        migrations.CreateModel(
            name="LOA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foreground",
                    models.FileField(
                        upload_to=analyses.models.data_path,
                        validators=[analyses.models.validate_file],
                    ),
                ),
                (
                    "background",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analyses.models.data_path,
                        validators=[analyses.models.validate_file],
                    ),
                ),
                ("require_same_strandedness", models.BooleanField(default=False)),
                (
                    "minimum_overlap_required",
                    models.FloatField(
                        default=1e-09,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "significance_level",
                    models.FloatField(
                        default=0.05,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "correction_method",
                    models.CharField(
                        choices=[
                            ("bonferroni", "Bonferroni"),
                            ("sidak", "Šidák"),
                            ("holm", "Holm"),
                            ("holm-sidak", "Holm-Šidák"),
                            ("smm", "Simes-Hochberg"),
                            ("hommel", "Hommel"),
                            ("fdr_bh", "Benjamini/Hochberg (FDR)"),
                            ("fdr_by", "Benjamini/Yekutieli (FDR)"),
                            ("fdr_tsbh", "Two-stage Benjamini/Hochberg (FDR)"),
                            (
                                "fdr_tsbky",
                                "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                            ),
                        ],
                        default="fdr_by",
                    ),
                ),
                ("results", models.JSONField(blank=True, editable=False, null=True)),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to=analyses.models.data_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "analysis_task",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_results.taskresult",
                    ),
                ),
                (
                    "reference_genome",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference_genomes.referencegenome",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LOA",
            },
        ),
        migrations.DeleteModel(
            name="GSEAAnalysis",
        ),
    ]
