# Generated by Django 5.2.4 on 2025-09-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0006_gsea_loa_delete_gseaanalysis"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gsea",
            old_name="analysis_task",
            new_name="task",
        ),
        migrations.RenameField(
            model_name="loa",
            old_name="analysis_task",
            new_name="task",
        ),
    ]
