# Generated by Django 5.2.4 on 2025-09-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0007_rename_analysis_task_gsea_task_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gsea",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="loa",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
