# Generated by Django 5.2.4 on 2025-09-19 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0009_remove_gsea_result_file_remove_loa_result_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="gsea",
            name="correction_method",
            field=models.CharField(
                choices=[
                    ("bonferroni", "Bonferroni"),
                    ("sidak", "Sidak"),
                    ("holm", "Holm"),
                    ("holm-sidak", "Holm-Sidak"),
                    ("smm", "Simes-Hochberg"),
                    ("hommel", "Hommel"),
                    ("fdr_bh", "Benjamini/Hochberg (FDR)"),
                    ("fdr_by", "Benjamini/Yekutieli (FDR)"),
                    ("fdr_tsbh", "Two-stage Benjamini/Hochberg (FDR)"),
                    ("fdr_tsbky", "Two-stage Benjamini/Krieger/Yekutieli (FDR)"),
                ],
                default="fdr_by",
            ),
        ),
        migrations.AlterField(
            model_name="gsea",
            name="submitter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="gsea",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="loa",
            name="correction_method",
            field=models.CharField(
                choices=[
                    ("bonferroni", "Bonferroni"),
                    ("sidak", "Sidak"),
                    ("holm", "Holm"),
                    ("holm-sidak", "Holm-Sidak"),
                    ("smm", "Simes-Hochberg"),
                    ("hommel", "Hommel"),
                    ("fdr_bh", "Benjamini/Hochberg (FDR)"),
                    ("fdr_by", "Benjamini/Yekutieli (FDR)"),
                    ("fdr_tsbh", "Two-stage Benjamini/Hochberg (FDR)"),
                    ("fdr_tsbky", "Two-stage Benjamini/Krieger/Yekutieli (FDR)"),
                ],
                default="fdr_by",
            ),
        ),
        migrations.AlterField(
            model_name="loa",
            name="submitter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="loa",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
