# Generated by Django 5.2.4 on 2025-09-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0011_alter_gsea_universe"),
        (
            "reference_genomes",
            "0004_remove_referencegenome_chrom_size_file_index_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="loa",
            name="universe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reference_genomes.genomicfeature",
            ),
        ),
    ]
