# Generated by Django 5.2.4 on 2025-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0012_loa_universe"),
        (
            "reference_genomes",
            "0004_remove_referencegenome_chrom_size_file_index_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loa",
            name="universe",
        ),
        migrations.AddField(
            model_name="loa",
            name="universe",
            field=models.ManyToManyField(
                blank=True,
                related_name="loa_universes",
                to="reference_genomes.genomicfeature",
            ),
        ),
    ]
