# Generated by Django 5.2.4 on 2025-10-01 07:13

import analyses.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0013_remove_loa_universe_loa_universe"),
        ("django_celery_results", "0014_alter_taskresult_status"),
        (
            "reference_genomes",
            "0004_remove_referencegenome_chrom_size_file_index_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="gsea",
            name="background_genes",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="gsea",
            name="foreground_genes",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="loa",
            name="background_genes",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="loa",
            name="foreground_genes",
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="SOA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                (
                    "foreground",
                    models.FileField(
                        upload_to=analyses.models.data_path,
                        validators=[analyses.models.validate_file],
                    ),
                ),
                (
                    "background",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=analyses.models.data_path,
                        validators=[analyses.models.validate_file],
                    ),
                ),
                ("require_same_strandedness", models.BooleanField(default=False)),
                (
                    "minimum_overlap_required",
                    models.FloatField(
                        default=1e-09,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "significance_level",
                    models.FloatField(
                        default=0.05,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "correction_method",
                    models.CharField(
                        choices=[
                            ("bonferroni", "Bonferroni"),
                            ("sidak", "Sidak"),
                            ("holm", "Holm"),
                            ("holm-sidak", "Holm-Sidak"),
                            ("smm", "Simes-Hochberg"),
                            ("hommel", "Hommel"),
                            ("fdr_bh", "Benjamini/Hochberg (FDR)"),
                            ("fdr_by", "Benjamini/Yekutieli (FDR)"),
                            ("fdr_tsbh", "Two-stage Benjamini/Hochberg (FDR)"),
                            (
                                "fdr_tsbky",
                                "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                            ),
                        ],
                        default="fdr_by",
                    ),
                ),
                (
                    "foreground_genes",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                (
                    "background_genes",
                    models.JSONField(blank=True, editable=False, null=True),
                ),
                ("results", models.JSONField(blank=True, editable=False, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reference_genome",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reference_genomes.referencegenome",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_celery_results.taskresult",
                    ),
                ),
                (
                    "universe",
                    models.ManyToManyField(
                        blank=True,
                        related_name="soa_universes",
                        to="reference_genomes.genomicfeature",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SOA",
            },
        ),
    ]
