# Generated by Django 5.2.4 on 2025-10-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0014_gsea_background_genes_gsea_foreground_genes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loa",
            name="background_genes",
        ),
        migrations.RemoveField(
            model_name="loa",
            name="foreground_genes",
        ),
        migrations.RemoveField(
            model_name="soa",
            name="background_genes",
        ),
        migrations.RemoveField(
            model_name="soa",
            name="foreground_genes",
        ),
    ]
