# Generated by Django 5.2.4 on 2025-10-01 12:50

import analyses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0015_remove_loa_background_genes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gsea",
            name="background_genes",
        ),
        migrations.RemoveField(
            model_name="gsea",
            name="foreground_genes",
        ),
        migrations.AddField(
            model_name="gsea",
            name="annotated_background",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to=analyses.models.data_path,
            ),
        ),
        migrations.AddField(
            model_name="gsea",
            name="annotated_foreground",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to=analyses.models.data_path,
            ),
        ),
    ]
