# Generated by Django 5.2.4 on 2025-10-01 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0016_remove_gsea_background_genes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gsea",
            name="correction_method",
            field=models.CharField(
                choices=[
                    ("Bonferroni", "Bonferroni"),
                    ("Sidak", "Sidak"),
                    ("Holm", "Holm"),
                    ("Holm-Sidak", "Holm-Sidak"),
                    ("Simes-Hochberg", "Simes-Hochberg"),
                    ("Hommel", "Hommel"),
                    ("Benjamini/Hochberg (FDR)", "Benjamini/Hochberg (FDR)"),
                    ("Benjamini/Yekutieli (FDR)", "Benjamini/Yekutieli (FDR)"),
                    (
                        "Two-stage Benjamini/Hochberg (FDR)",
                        "Two-stage Benjamini/Hochberg (FDR)",
                    ),
                    (
                        "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                        "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                    ),
                ],
                default="Benjamini/Yekutieli (FDR)",
            ),
        ),
        migrations.AlterField(
            model_name="gsea",
            name="universe",
            field=models.CharField(
                choices=[
                    ("H", "Hallmark"),
                    ("C1", "Positional gene sets"),
                    ("C2", "Curated gene sets"),
                    ("C3", "Regulatory target gene sets"),
                    ("C4", "Computational gene sets"),
                    ("C5", "Ontology gene sets"),
                    ("C6", "Oncogenic signature gene sets"),
                    ("C7", "Immunologic signature gene sets"),
                    ("C8", "Cell type signature gene sets"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="loa",
            name="correction_method",
            field=models.CharField(
                choices=[
                    ("Bonferroni", "Bonferroni"),
                    ("Sidak", "Sidak"),
                    ("Holm", "Holm"),
                    ("Holm-Sidak", "Holm-Sidak"),
                    ("Simes-Hochberg", "Simes-Hochberg"),
                    ("Hommel", "Hommel"),
                    ("Benjamini/Hochberg (FDR)", "Benjamini/Hochberg (FDR)"),
                    ("Benjamini/Yekutieli (FDR)", "Benjamini/Yekutieli (FDR)"),
                    (
                        "Two-stage Benjamini/Hochberg (FDR)",
                        "Two-stage Benjamini/Hochberg (FDR)",
                    ),
                    (
                        "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                        "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                    ),
                ],
                default="Benjamini/Yekutieli (FDR)",
            ),
        ),
        migrations.AlterField(
            model_name="soa",
            name="correction_method",
            field=models.CharField(
                choices=[
                    ("Bonferroni", "Bonferroni"),
                    ("Sidak", "Sidak"),
                    ("Holm", "Holm"),
                    ("Holm-Sidak", "Holm-Sidak"),
                    ("Simes-Hochberg", "Simes-Hochberg"),
                    ("Hommel", "Hommel"),
                    ("Benjamini/Hochberg (FDR)", "Benjamini/Hochberg (FDR)"),
                    ("Benjamini/Yekutieli (FDR)", "Benjamini/Yekutieli (FDR)"),
                    (
                        "Two-stage Benjamini/Hochberg (FDR)",
                        "Two-stage Benjamini/Hochberg (FDR)",
                    ),
                    (
                        "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                        "Two-stage Benjamini/Krieger/Yekutieli (FDR)",
                    ),
                ],
                default="Benjamini/Yekutieli (FDR)",
            ),
        ),
    ]
