# Generated by Django 5.2.4 on 2025-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0019_alter_gsea_universe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gsea",
            name="universe",
            field=models.CharField(
                blank=True,
                choices=[
                    ("H", "Hallmark"),
                    ("C1", "Positional gene sets"),
                    ("C2", "Curated gene sets"),
                    ("C3", "Regulatory target gene sets"),
                    ("C4", "Computational gene sets"),
                    ("C5", "Ontology gene sets"),
                    ("C6", "Oncogenic signature gene sets"),
                    ("C7", "Immunologic signature gene sets"),
                    ("C8", "Cell type signature gene sets"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
