# Generated by Django 5.2.4 on 2025-10-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0021_alter_gsea_correction_method_alter_gsea_universe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loa",
            name="permutations",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
