# Generated by Django 5.2.4 on 2025-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0022_loa_permutations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loa",
            name="permutations",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
