# Generated by Django 5.2.4 on 2025-10-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0023_alter_loa_permutations"),
        (
            "reference_genomes",
            "0009_remove_geneset_msigdb_url_remove_genomicfeature_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="loa",
            name="permutations",
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name="loa",
            name="universe",
            field=models.ManyToManyField(
                related_name="loa_universes", to="reference_genomes.genomicfeature"
            ),
        ),
    ]
