# Generated by Django 5.2.4 on 2025-10-05 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0024_alter_loa_permutations_alter_loa_universe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soa",
            name="significance_level",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ]
            ),
        ),
    ]
