# Generated by Django 5.2.4 on 2025-10-05 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0025_alter_soa_significance_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="soa",
            name="significance_level",
            field=models.FloatField(
                default=0.05,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
