# Generated by Django 5.2.4 on 2025-10-06 08:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0026_alter_soa_significance_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="gsea",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("CDS", "CDS"),
                    ("C_gene_segment", "C_gene_segment"),
                    ("J_gene_segment", "J_gene_segment"),
                    ("V_gene_segment", "V_gene_segment"),
                    ("exon", "exon"),
                    ("five_prime_UTR", "five_prime_UTR"),
                    ("gene", "gene"),
                    ("mRNA", "mRNA"),
                    ("miRNA", "miRNA"),
                    ("pseudogene", "pseudogene"),
                    ("pseudogenic_transcript", "pseudogenic_transcript"),
                    ("rRNA", "rRNA"),
                    ("snRNA", "snRNA"),
                    ("snoRNA", "snoRNA"),
                    ("three_prime_UTR", "three_prime_UTR"),
                ],
                default="gene",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="gsea",
            name="input_type",
            field=models.CharField(
                choices=[
                    ("genomic_intervals", "Genomic Intervals"),
                    ("gene_names", "Gene Names"),
                ],
                default="gene_names",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gsea",
            name="max_absolute_distance",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="gsea",
            name="n_closest",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
