# Generated by Django 5.2.4 on 2025-10-06 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0027_gsea_feature_type_gsea_input_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gsea",
            name="feature_type",
            field=models.CharField(
                choices=[
                    ("CDS", "CDS"),
                    ("C_gene_segment", "C gene segment"),
                    ("J_gene_segment", "J gene segment"),
                    ("V_gene_segment", "V gene segment"),
                    ("exon", "exon"),
                    ("five_prime_UTR", "five` UTR"),
                    ("gene", "gene"),
                    ("mRNA", "mRNA"),
                    ("miRNA", "miRNA"),
                    ("pseudogene", "pseudogene"),
                    ("pseudogenic_transcript", "pseudogenic transcript"),
                    ("rRNA", "rRNA"),
                    ("snRNA", "snRNA"),
                    ("snoRNA", "snoRNA"),
                    ("three_prime_UTR", "three` UTR"),
                ],
                default="gene",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="gsea",
            name="max_absolute_distance",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
    ]
