# Generated by Django 5.2.4 on 2025-10-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0028_alter_gsea_feature_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gsea",
            name="feature_type",
        ),
    ]
