# Generated by Django 5.2.4 on 2025-10-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0029_remove_gsea_feature_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="loa",
            name="alternative",
            field=models.CharField(
                choices=[
                    ("greater", "Enrichment"),
                    ("less", "Depletion"),
                    ("two-sided", "Both"),
                ],
                default="two-sided",
                max_length=20,
            ),
        ),
    ]
