# Generated by Django 5.2.4 on 2025-10-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0030_loa_alternative"),
        (
            "reference_genomes",
            "0017_genomicfeaturecollection_genomicfeature_collection",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="soa",
            name="universe",
        ),
        migrations.AlterField(
            model_name="loa",
            name="universe",
            field=models.ManyToManyField(
                related_name="loa_universes",
                to="reference_genomes.genomicfeaturecollection",
            ),
        ),
    ]
