# Generated by Django 5.2.4 on 2025-10-14 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0031_remove_soa_universe_alter_loa_universe"),
        (
            "reference_genomes",
            "0017_genomicfeaturecollection_genomicfeature_collection",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loa",
            name="universe",
        ),
        migrations.AddField(
            model_name="loa",
            name="universe",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loa_universes",
                to="reference_genomes.genomicfeaturecollection",
            ),
        ),
    ]
