# Generated by Django 5.2.4 on 2025-10-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analyses", "0032_remove_loa_universe_loa_universe"),
        (
            "reference_genomes",
            "0017_genomicfeaturecollection_genomicfeature_collection",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loa",
            name="universe",
        ),
        migrations.AddField(
            model_name="loa",
            name="universe",
            field=models.ManyToManyField(
                null=True,
                related_name="loa_universes",
                to="reference_genomes.genomicfeaturecollection",
            ),
        ),
    ]
