# Generated by Django 5.2.4 on 2025-10-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0034_alter_loa_universe'),
    ]

    operations = [
        migrations.AddField(
            model_name='soa',
            name='study_type',
            field=models.CharField(choices=[('association_study', 'Association Studies'), ('interaction_study', 'Interaction Studies'), ('profiling_study', 'Profiling Studies')], default='association_study', max_length=50),
        ),
    ]
