# Generated by Django 5.2.7 on 2025-10-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0035_soa_study_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loa',
            name='lift_over_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
