# Generated by Django 5.2.7 on 2025-10-19 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0036_loa_lift_over_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='gsea',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loa',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soa',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
