# Generated by Django 5.2.7 on 2025-11-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0037_gsea_public_loa_public_soa_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsea',
            name='universe',
            field=models.CharField(blank=True, choices=[('Hallmark (H)', 'Hallmark (H)'), ('Positional gene sets (C1)', 'Positional gene sets (C1)'), ('Curated gene sets (C2)', 'Curated gene sets (C2)'), ('Regulatory target gene sets (C3)', 'Regulatory target gene sets (C3)'), ('Computational gene sets (C4)', 'Computational gene sets (C4)'), ('Ontology gene sets (C5)', 'Ontology gene sets (C5)'), ('Oncogenic signature gene sets (C6)', 'Oncogenic signature gene sets (C6)'), ('Immunologic signature gene sets (C7)', 'Immunologic signature gene sets (C7)'), ('Cell type signature gene sets (C8)', 'Cell type signature gene sets (C8)')], default=None, null=True),
        ),
    ]
