# Generated by Django 5.2.4 on 2025-09-10 11:46

import django.core.files.storage
import studies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studydata",
            name="preprocessed_data",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    file_permissions_mode=438
                ),
                upload_to=studies.models.data_path,
                validators=[studies.models.validate_file_name],
            ),
        ),
        migrations.AddField(
            model_name="studydata",
            name="preprocessed_data_checksum",
            field=models.CharField(blank=True, editable=False, null=True),
        ),
    ]
