# Generated by Django 5.2.4 on 2025-09-10 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0003_studydata_preprocessed_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "raw_data_storage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sra", "SRA"),
                            ("geo", "GEO"),
                            ("ega", "EGA"),
                            ("array_express", "Array Express"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "raw_data_accession_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="studydata",
            old_name="submitted_data",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="studydata",
            old_name="preprocessed_data_checksum",
            new_name="data_checksum",
        ),
        migrations.RemoveField(
            model_name="studydata",
            name="preprocessed_data",
        ),
        migrations.RemoveField(
            model_name="studydata",
            name="raw_data_accession_number",
        ),
        migrations.RemoveField(
            model_name="studydata",
            name="raw_data_storage",
        ),
        migrations.RemoveField(
            model_name="studydata",
            name="submitted_data_checksum",
        ),
        migrations.AddField(
            model_name="associationstudy",
            name="preprocessed_data",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="studies.studydata",
            ),
        ),
        migrations.AddField(
            model_name="associationstudy",
            name="submitted_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="studies.studydata",
            ),
        ),
        migrations.AddField(
            model_name="interactionstudy",
            name="preprocessed_data",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="studies.studydata",
            ),
        ),
        migrations.AddField(
            model_name="interactionstudy",
            name="submitted_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="studies.studydata",
            ),
        ),
        migrations.AddField(
            model_name="profilingstudy",
            name="preprocessed_data",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="studies.studydata",
            ),
        ),
        migrations.AddField(
            model_name="profilingstudy",
            name="submitted_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="studies.studydata",
            ),
        ),
    ]
