# Generated by Django 5.2.4 on 2025-09-10 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0004_datastorage_rename_submitted_data_studydata_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="associationstudy",
            name="data",
        ),
        migrations.RemoveField(
            model_name="interactionstudy",
            name="data",
        ),
        migrations.RemoveField(
            model_name="profilingstudy",
            name="data",
        ),
        migrations.AlterField(
            model_name="associationstudy",
            name="preprocessed_data",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ps_association_study",
                to="studies.studydata",
            ),
        ),
        migrations.AlterField(
            model_name="associationstudy",
            name="submitted_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sd_association_study",
                to="studies.studydata",
            ),
        ),
        migrations.AlterField(
            model_name="interactionstudy",
            name="preprocessed_data",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ps_interaction_study",
                to="studies.studydata",
            ),
        ),
        migrations.AlterField(
            model_name="interactionstudy",
            name="submitted_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sd_interaction_study",
                to="studies.studydata",
            ),
        ),
        migrations.AlterField(
            model_name="profilingstudy",
            name="preprocessed_data",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pd_profiling_study",
                to="studies.studydata",
            ),
        ),
        migrations.AlterField(
            model_name="profilingstudy",
            name="submitted_data",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sd_profiling_study",
                to="studies.studydata",
            ),
        ),
    ]
