# Generated by Django 5.2.4 on 2025-09-10 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0005_remove_associationstudy_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationstudy",
            name="submitted_data",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sd_association_study",
                to="studies.studydata",
            ),
        ),
        migrations.AlterField(
            model_name="interactionstudy",
            name="submitted_data",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sd_interaction_study",
                to="studies.studydata",
            ),
        ),
        migrations.AlterField(
            model_name="profilingstudy",
            name="submitted_data",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sd_profiling_study",
                to="studies.studydata",
            ),
        ),
    ]
