# Generated by Django 5.2.4 on 2025-09-14 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0007_alter_associationstudy_biosample_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associationstudy",
            name="embedding",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="studies.embedding",
            ),
        ),
        migrations.AlterField(
            model_name="interactionstudy",
            name="embedding",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="studies.embedding",
            ),
        ),
        migrations.AlterField(
            model_name="profilingstudy",
            name="embedding",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="studies.embedding",
            ),
        ),
    ]
