# Generated by Django 5.2.4 on 2025-09-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0008_alter_associationstudy_embedding_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contact",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
