# Generated by Django 5.2.4 on 2025-10-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0009_alter_project_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationstudy",
            name="plots",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interactionstudy",
            name="plots",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profilingstudy",
            name="plots",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
