# Generated by Django 5.2.4 on 2025-10-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0010_associationstudy_plots_interactionstudy_plots_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="associationstudy",
            name="plots",
        ),
        migrations.RemoveField(
            model_name="interactionstudy",
            name="plots",
        ),
        migrations.RemoveField(
            model_name="profilingstudy",
            name="plots",
        ),
    ]
