# Generated by Django 5.2.4 on 2025-10-16 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0011_remove_associationstudy_plots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationstudy',
            name='raw_data_storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.datastorage'),
        ),
        migrations.AddField(
            model_name='interactionstudy',
            name='phenotype',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.phenotype'),
        ),
        migrations.AddField(
            model_name='interactionstudy',
            name='raw_data_storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.datastorage'),
        ),
        migrations.AddField(
            model_name='profilingstudy',
            name='phenotype',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.phenotype'),
        ),
        migrations.AddField(
            model_name='profilingstudy',
            name='raw_data_storage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.datastorage'),
        ),
    ]
