# Generated by Django 5.2.4 on 2025-10-17 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ontologies', '0002_alter_anatomicalstructure_options_and_more'),
        ('studies', '0012_associationstudy_raw_data_storage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biosample',
            name='cell_line',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'cell_line'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ontologies.term'),
        ),
        migrations.AlterField(
            model_name='interactionstudy',
            name='phenotype',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.phenotype'),
        ),
        migrations.AlterField(
            model_name='profilingstudy',
            name='phenotype',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studies.phenotype'),
        ),
    ]
