# Generated by Django 5.2.4 on 2025-09-25 08:27

import django.core.files.storage
import reference_genomes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0003_alter_geneset_collection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referencegenome",
            name="chrom_size_file_index",
        ),
        migrations.RemoveField(
            model_name="referencegenome",
            name="chrom_size_file_index_checksum",
        ),
        migrations.AddField(
            model_name="referencegenome",
            name="chrom_size_file_bed",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    allow_overwrite=True, file_permissions_mode=438
                ),
                upload_to=reference_genomes.models.upload_chrom_size_file,
            ),
        ),
        migrations.AddField(
            model_name="referencegenome",
            name="chrom_size_file_bed_checksum",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="referencegenome",
            name="chrom_size_file_bed_index",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    allow_overwrite=True, file_permissions_mode=438
                ),
                upload_to=reference_genomes.models.upload_chrom_size_file,
            ),
        ),
        migrations.AddField(
            model_name="referencegenome",
            name="chrom_size_file_bed_index_checksum",
            field=models.CharField(blank=True, null=True),
        ),
    ]
