# Generated by Django 5.2.4 on 2025-10-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0006_alter_geneset_collection_alter_geneset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geneset",
            name="name",
            field=models.CharField(max_length=666, unique=True),
        ),
    ]
