# Generated by Django 5.2.4 on 2025-10-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0007_alter_geneset_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geneset",
            name="name",
            field=models.CharField(unique=True),
        ),
    ]
