# Generated by Django 5.2.4 on 2025-10-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0008_alter_geneset_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="geneset",
            name="msigdb_url",
        ),
        migrations.RemoveField(
            model_name="genomicfeature",
            name="type",
        ),
        migrations.AddField(
            model_name="genomicfeature",
            name="reference_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
