# Generated by Django 5.2.4 on 2025-10-05 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference_genomes",
            "0009_remove_geneset_msigdb_url_remove_genomicfeature_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="geneset",
            old_name="exact_source",
            new_name="reference",
        ),
        migrations.RenameField(
            model_name="geneset",
            old_name="external_details_url",
            new_name="reference_url",
        ),
        migrations.AddField(
            model_name="genomicfeature",
            name="reference",
            field=models.TextField(blank=True, null=True),
        ),
    ]
