# Generated by Django 5.2.4 on 2025-10-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0010_rename_exact_source_geneset_reference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="geneset",
            name="exact_source",
            field=models.CharField(blank=True, null=True),
        ),
    ]
