# Generated by Django 5.2.4 on 2025-10-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0011_geneset_exact_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="geneset",
            name="external_details_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
