# Generated by Django 5.2.4 on 2025-10-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0012_geneset_external_details_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geneset",
            name="name",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
