# Generated by Django 5.2.4 on 2025-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0013_alter_geneset_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="genomicfeature",
            name="collection",
            field=models.CharField(blank=True, null=True),
        ),
    ]
