# Generated by Django 5.2.4 on 2025-10-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0014_genomicfeature_collection"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="geneset",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="genomicfeature",
            options={"ordering": ["name"], "verbose_name_plural": "Genomic Features"},
        ),
    ]
