# Generated by Django 5.2.4 on 2025-10-13 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference_genomes",
            "0015_alter_geneset_options_alter_genomicfeature_options",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genomicfeature",
            name="collection",
        ),
    ]
