# Generated by Django 5.2.4 on 2025-10-13 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference_genomes", "0016_remove_genomicfeature_collection"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenomicFeatureCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("reference", models.TextField(blank=True, null=True)),
                ("reference_url", models.URLField(blank=True, null=True)),
                (
                    "reference_genome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_collections",
                        to="reference_genomes.referencegenome",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Genomic Feature Collections",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="genomicfeature",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="reference_genomes.genomicfeaturecollection",
            ),
        ),
    ]
