# Generated by Django 5.2.7 on 2025-12-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_genomes', '0018_alter_geneset_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneset',
            name='systematic_name',
            field=models.CharField(max_length=512),
        ),
    ]
