# Generated by Django 5.2.7 on 2025-12-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_genomes', '0019_alter_geneset_systematic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneset',
            name='reference_url',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
    ]
