# Generated by Django 5.2.4 on 2025-09-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnatomicalStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obo_id",
                    models.CharField(
                        help_text="OBO resource identifier", max_length=25, unique=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Human readable name", null=True
                    ),
                ),
                (
                    "synonyms",
                    models.CharField(blank=True, help_text="Synonym(s)", null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Precise term description", null=True
                    ),
                ),
                (
                    "ontology_name",
                    models.TextField(blank=True, help_text="Data source", null=True),
                ),
                (
                    "iri",
                    models.URLField(
                        blank=True, help_text="Link to the resource", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Anatomical structures",
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obo_id",
                    models.CharField(
                        help_text="OBO resource identifier", max_length=25, unique=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Human readable name", null=True
                    ),
                ),
                (
                    "synonyms",
                    models.CharField(blank=True, help_text="Synonym(s)", null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Precise term description", null=True
                    ),
                ),
                (
                    "ontology_name",
                    models.TextField(blank=True, help_text="Data source", null=True),
                ),
                (
                    "iri",
                    models.URLField(
                        blank=True, help_text="Link to the resource", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("investigation_model", "Investigation Model"),
                            ("effect_size_metric", "Effect size metric"),
                            ("statistical_test", "Statistical test"),
                            ("cell_line", "Cell line"),
                            ("substance", "Substance"),
                            ("phenotype", "Phenotype"),
                            ("platform", "Platform"),
                            ("analyte", "Analyte"),
                            ("target", "Target"),
                            ("assay", "Assay"),
                        ]
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Experiment Terms",
            },
        ),
        migrations.CreateModel(
            name="CellType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "obo_id",
                    models.CharField(
                        help_text="OBO resource identifier", max_length=25, unique=True
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Human readable name", null=True
                    ),
                ),
                (
                    "synonyms",
                    models.CharField(blank=True, help_text="Synonym(s)", null=True),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Precise term description", null=True
                    ),
                ),
                (
                    "ontology_name",
                    models.TextField(blank=True, help_text="Data source", null=True),
                ),
                (
                    "iri",
                    models.URLField(
                        blank=True, help_text="Link to the resource", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "anatomical_structure",
                    models.ManyToManyField(
                        help_text="Anatomical structure this cell type belongs to",
                        related_name="cell_types",
                        to="ontologies.anatomicalstructure",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Cell types",
            },
        ),
    ]
