# Generated by Django 5.2.4 on 2025-10-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ontologies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anatomicalstructure',
            options={'ordering': ['label'], 'verbose_name_plural': 'Anatomical structures'},
        ),
        migrations.AlterModelOptions(
            name='celltype',
            options={'ordering': ['label'], 'verbose_name_plural': 'Cell types'},
        ),
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['label'], 'verbose_name_plural': 'Experiment Terms'},
        ),
    ]
